package program_apotik;

import java.beans.PropertyVetoException;

/**
 *
 * @author Asus
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MDI = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuLogout = new javax.swing.JMenuItem();
        jMenuRegister = new javax.swing.JMenuItem();
        jMenuExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuObat = new javax.swing.JMenuItem();
        jMenuSuplier = new javax.swing.JMenuItem();
        jMenuKaryawan = new javax.swing.JMenuItem();
        jMenuTransaksi = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuInputSuplier = new javax.swing.JMenuItem();
        jMenuInpuKaryawan = new javax.swing.JMenuItem();
        jMenuInputTransaksi = new javax.swing.JMenuItem();
        jMenuInputObat = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuEditSuplier = new javax.swing.JMenuItem();
        jMenuEditObat = new javax.swing.JMenuItem();
        jMenuEditKaryawan = new javax.swing.JMenuItem();
        jMenuCetakTr = new javax.swing.JMenu();
        CetakTr = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Apotik");

        MDI.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout MDILayout = new javax.swing.GroupLayout(MDI);
        MDI.setLayout(MDILayout);
        MDILayout.setHorizontalGroup(
            MDILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 523, Short.MAX_VALUE)
        );
        MDILayout.setVerticalGroup(
            MDILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 374, Short.MAX_VALUE)
        );

        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenu1.setText("Menu");

        jMenuLogout.setText("Log Out");
        jMenuLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuLogout);

        jMenuRegister.setText("Register");
        jMenuRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRegisterActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuRegister);

        jMenuExit.setText("Exit");
        jMenuExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuExitActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Master data");

        jMenuObat.setText("Data Obat");
        jMenuObat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuObatActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuObat);

        jMenuSuplier.setText("Data Suplier");
        jMenuSuplier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuSuplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSuplierActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuSuplier);

        jMenuKaryawan.setText("Data karyawan");
        jMenuKaryawan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuKaryawanActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuKaryawan);

        jMenuTransaksi.setText("Data Transaksi");
        jMenuTransaksi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuTransaksiActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuTransaksi);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Input");

        jMenuInputSuplier.setText("Input Data Suplier");
        jMenuInputSuplier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuInputSuplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuInputSuplierActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuInputSuplier);

        jMenuInpuKaryawan.setText("Input Data Karyawan");
        jMenuInpuKaryawan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuInpuKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuInpuKaryawanActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuInpuKaryawan);

        jMenuInputTransaksi.setText("Input Data Transaksi");
        jMenuInputTransaksi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuInputTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuInputTransaksiActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuInputTransaksi);

        jMenuInputObat.setText("Input Data Obat");
        jMenuInputObat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuInputObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuInputObatActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuInputObat);

        jMenuBar1.add(jMenu4);

        jMenu3.setText("Edit Dan Hapus");
        jMenu3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenuEditSuplier.setText("Edit Data Suplier");
        jMenuEditSuplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEditSuplierActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuEditSuplier);

        jMenuEditObat.setText("Edit Data Obat");
        jMenuEditObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEditObatActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuEditObat);

        jMenuEditKaryawan.setText("Edit Data Karyawan");
        jMenuEditKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEditKaryawanActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuEditKaryawan);

        jMenuBar1.add(jMenu3);

        jMenuCetakTr.setText("Cetak Transaksi");
        jMenuCetakTr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCetakTrActionPerformed(evt);
            }
        });

        CetakTr.setText("Cetak");
        CetakTr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CetakTrActionPerformed(evt);
            }
        });
        jMenuCetakTr.add(CetakTr);

        jMenuBar1.add(jMenuCetakTr);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MDI)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MDI, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        setBounds(0, 0, 537, 404);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuKaryawanActionPerformed
        // TODO add your handling code here:
        datakaryawan datakaryawan = new datakaryawan();
        if (datakaryawan.isVisible()){ 
            try{ 
                datakaryawan.setSelected(true); 
            }catch (PropertyVetoException ex) {} 
        }else { datakaryawan = new datakaryawan(); 
            MDI.add(datakaryawan); datakaryawan.setVisible(true); 
        }
    }//GEN-LAST:event_jMenuKaryawanActionPerformed

    private void jMenuInputTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuInputTransaksiActionPerformed
        // TODO add your handling code here:
        input_transaksi input_transaksi=new input_transaksi();
        if (input_transaksi.isVisible()){ 
            try{ 
                input_transaksi.setSelected(true); 
            }catch (PropertyVetoException ex) {} 
        }else{ 
            input_transaksi = new input_transaksi(); 
            MDI.add(input_transaksi); input_transaksi.setVisible(true); 
        }
    }//GEN-LAST:event_jMenuInputTransaksiActionPerformed

    private void jMenuInputObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuInputObatActionPerformed
        // TODO add your handling code here:
        input_obat input_obat = new input_obat();
        if (input_obat.isVisible()){ 
            try{ 
                input_obat.setSelected(true); 
            }catch (PropertyVetoException ex) {} 
        }else { input_obat = new input_obat(); 
            MDI.add(input_obat); input_obat.setVisible(true); 
        }
    }//GEN-LAST:event_jMenuInputObatActionPerformed

    private void jMenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuExitActionPerformed
        // TODO add your handling code here:
       System.exit(0);
    }//GEN-LAST:event_jMenuExitActionPerformed

    private void jMenuEditSuplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEditSuplierActionPerformed
        // TODO add your handling code here:
        edit_suplier edit_suplier = new edit_suplier();
        if (edit_suplier.isVisible()){ 
            try{
                edit_suplier.setSelected(true); 
            }catch (PropertyVetoException ex) {} 
        }else { 
            edit_suplier = new edit_suplier(); 
            MDI.add(edit_suplier); edit_suplier.setVisible(true); 
        }
    }//GEN-LAST:event_jMenuEditSuplierActionPerformed

    private void jMenuInpuKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuInpuKaryawanActionPerformed
        // TODO add your handling code here:
        input_karyawan input_karyawan = new input_karyawan();
        if (input_karyawan.isVisible()) { 
            try { 
                input_karyawan.setSelected(true); 
            }catch (PropertyVetoException ex) {} 
        }else { 
            input_karyawan = new input_karyawan(); 
            MDI.add(input_karyawan); input_karyawan.setVisible(true); 
        }
    }//GEN-LAST:event_jMenuInpuKaryawanActionPerformed

    private void jMenuInputSuplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuInputSuplierActionPerformed
        // TODO add your handling code here:
        input_Suplier input_Suplier = new input_Suplier();
        if (input_Suplier.isVisible()) { 
            try { 
                input_Suplier.setSelected(true); 
            }catch (PropertyVetoException ex) {} 
        }else { 
            input_Suplier = new input_Suplier(); 
            MDI.add(input_Suplier); input_Suplier.setVisible(true); 
        }
    }//GEN-LAST:event_jMenuInputSuplierActionPerformed

    private void jMenuObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuObatActionPerformed
        // TODO add your handling code here:
        dataobat dataobat = new dataobat();
        if (dataobat.isVisible()){ 
            try { 
                dataobat.setSelected(true); 
            }catch (PropertyVetoException ex) {} 
        }else { 
            dataobat = new dataobat(); 
            MDI.add(dataobat); dataobat.setVisible(true); 
        }
    }//GEN-LAST:event_jMenuObatActionPerformed

    private void jMenuTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuTransaksiActionPerformed
        // TODO add your handling code here:
        datatransaksi datatransaksi = new datatransaksi();
        if (datatransaksi.isVisible()){ 
           try { 
               datatransaksi.setSelected(true); 
           }catch (PropertyVetoException ex) {} 
        }else { 
            datatransaksi = new datatransaksi(); 
            MDI.add(datatransaksi); datatransaksi.setVisible(true); 
        }
    }//GEN-LAST:event_jMenuTransaksiActionPerformed

    private void jMenuSuplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSuplierActionPerformed
        // TODO add your handling code here:
        datasuplier datasuplier = new datasuplier();
        if (datasuplier.isVisible()){ 
            try { 
                datasuplier.setSelected(true); 
            }catch (PropertyVetoException ex) {} 
        }else { 
            datasuplier = new datasuplier(); 
            MDI.add(datasuplier); datasuplier.setVisible(true); 
        }
    }//GEN-LAST:event_jMenuSuplierActionPerformed

    private void jMenuEditObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEditObatActionPerformed
        // TODO add your handling code here:
        edit_obat edit_obat = new edit_obat();
        if (edit_obat.isVisible()){ 
            try { 
                edit_obat.setSelected(true); 
            }catch (PropertyVetoException ex) {} 
        }else { 
            edit_obat = new edit_obat(); 
            MDI.add(edit_obat); edit_obat.setVisible(true); 
        }
    }//GEN-LAST:event_jMenuEditObatActionPerformed

    private void jMenuEditKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEditKaryawanActionPerformed
        // TODO add your handling code here:
        edit_karyawan edit_karyawan = new edit_karyawan();
        if (edit_karyawan.isVisible()){ 
            try { 
                edit_karyawan.setSelected(true); 
            }catch (PropertyVetoException ex) {} 
        }else { 
            edit_karyawan = new edit_karyawan(); 
            MDI.add(edit_karyawan); edit_karyawan.setVisible(true); 
        }
    }//GEN-LAST:event_jMenuEditKaryawanActionPerformed

    private void jMenuCetakTrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCetakTrActionPerformed
        // TODO add your handling code here:
 
    }//GEN-LAST:event_jMenuCetakTrActionPerformed

    private void CetakTrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CetakTrActionPerformed
        // TODO add your handling code here:
        cetakdata cetakdata = new cetakdata();
        if (cetakdata.isVisible()){ 
            try { 
                cetakdata.setSelected(true); 
            }catch (PropertyVetoException ex) {} 
        }else { 
            cetakdata = new cetakdata(); 
            MDI.add(cetakdata); cetakdata.setVisible(true); 
        }
    }//GEN-LAST:event_CetakTrActionPerformed

    private void jMenuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLogoutActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuLogoutActionPerformed

    private void jMenuRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRegisterActionPerformed
        // TODO add your handling code here:
        Register Register = new Register();
        Register.setVisible(true);
        Register.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            Home home = new Home();
            home.setVisible(true);
            home.setLocationRelativeTo(null); 
        }
    });
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CetakTr;
    private javax.swing.JDesktopPane MDI;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCetakTr;
    private javax.swing.JMenuItem jMenuEditKaryawan;
    private javax.swing.JMenuItem jMenuEditObat;
    private javax.swing.JMenuItem jMenuEditSuplier;
    private javax.swing.JMenuItem jMenuExit;
    private javax.swing.JMenuItem jMenuInpuKaryawan;
    private javax.swing.JMenuItem jMenuInputObat;
    private javax.swing.JMenuItem jMenuInputSuplier;
    private javax.swing.JMenuItem jMenuInputTransaksi;
    private javax.swing.JMenuItem jMenuKaryawan;
    private javax.swing.JMenuItem jMenuLogout;
    private javax.swing.JMenuItem jMenuObat;
    private javax.swing.JMenuItem jMenuRegister;
    private javax.swing.JMenuItem jMenuSuplier;
    private javax.swing.JMenuItem jMenuTransaksi;
    // End of variables declaration//GEN-END:variables
}
